name: CRAN Checks

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master 

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3' 

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          install.packages(c("devtools", "rcmdcheck", "testthat", "roxygen2"), repos = "https://cloud.r-project.org")

      - name: Check package
        run: |
          Rscript -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")'